services:
  dragonwilds-companion:
    build: .
    container_name: dragonwilds-companion
    restart: unless-stopped
    ports:
      - "9876:9876"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/dragonwilds/server-files/RSDragonwilds/Saved/SaveGames:/savegames:ro
    environment:
      CONTAINER: runescape-dragonwilds
      SAVE_PATH: /savegames
      MAX_PLAYERS: 6
